### ISSUE TITLE
When will version 0.5 be released to maven central repository?

### ISSUE THREAD

**Issue by MBlokhuijzen** [rawls238/Scientist4J#24]
Just wondering when I can use it. Or what I can do to get it there?

**Comment by ArturGajowy** [comment]
You could try using jitpack.io till that happens :) https://jitpack.io/#rawls238/Scientist4J

**Comment by rawls238** [comment]
hi, sorry about this. I was having some problems with registering the newest version in maven and haven't had the bandwidth to debug them. I'll try to resolve them asap

**Comment by Swilvan** [comment]
@rawls238 I'd really like this version to be released (preferably including my currently open PR). I'd be willing to help you out maintaining this if you don't have time for it now. I could do what  @ArturGajowy  suggests and work around 0.5 not being released but I'd rather contribute to this very nice project. Please let me know what works for you :)

**Comment by rawls238** [comment]
Sorry! I will try to wrestle with the maven issues I've been running into again this weekend.

**Comment by rawls238** [comment]
hey all, I finally have managed to upload the artifacts for v0.5 Apologies this took so long. Let me know if you run into any issues!
