### ISSUE TITLE
Can experiment.run() accept a callable instead of a supplier?

### ISSUE THREAD

**Issue by RashmiRam** [rawls238/Scientist4J#32]
Currently, "run" method in experiment accepts a supplier for both control and candidate functions. This limits the usage of the experiments to be run only for those control functions where exceptions are not expected or is being ignored. 

Current Signature:
 public T run(Supplier<T> control, Supplier<T> candidate) throws Exception 

Proposed/Overloaded Signature:
public T run(Callable<T> control, Callable<T> candidate) throws Exception 

@rawls238 What do you think about this?  If you are okay with this, I am more than happy to raise a PR

**Comment by rawls238** [comment]
this sounds good, feel free to PR

**Comment by RashmiRam** [comment]
@rawls238 
Example:
I am refactoring a function where it calls third party services to check if an entity exists. 
public boolean findingResourceOldWay(...) throws NotFoundException # control method
{  
    ---old code ----
}

public boolean findingResourceNewWay(...) throws NotFoundException # candidate method
{  
    ---Refactored code ----
}

However the method signature is not changed on both control and candidate functions. Both of them throws NotFoundException if entity doesn't exists. If I want to run experiment on this function, supplier is not sufficient.

**Comment by RashmiRam** [comment]
#33

**Comment by rawls238** [comment]
closed by #33
