### ISSUE TITLE
Dependencies on Dropwizard metrics

### ISSUE THREAD

**Issue by Allsimon** [rawls238/Scientist4J#36]
Hello, 

I'm currently using Scientist4J but I'm not interested in having Dropwizard metrics in my dependencies since I'm already using another metrics library.

What do you think about splitting the current `Scientist4JCore` module in two modules: a proper `Scientist4JCore` and a `Scientist4JDropwizard` ?

If this is okay with you, I can open a PR for it. I can also provide another module `Scientist4JMicrometer` if you wish

**Comment by rawls238** [comment]
feel free to PR

**Comment by Allsimon** [comment]
Nevermind, I didn't see that Dropwizard MetricRegistry was part of the `Experiment` API, this might be a big breaking change...

**Comment by eager** [comment]
@Allsimon @rawls238 it’s currently a draft—I want to test with a real project this week—but I have a potential solution in #37.
