### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by BGordts** [rawls238/Scientist4J#8]
First of all: I'm rather new to maven, so probably I'm doing something wrong. Sorry if that would be the case.

When I add this dependency to my maven POM, and then do `mvn compile` or `mvn clean install -U`, I get the following error: http://i.imgur.com/ia8XUFp.png.

**Comment by rawls238** [comment]
Sorry about this, the artifact mentioned in the README is not the default one you should pull in.

You should define the dependency as:
```
<dependency>
   <groupId>com.github.rawls238</groupId>
   <artifactId>Scientist4JCore</artifactId>
   <version>0.1</version>
</dependency>
```

Let me know if that fixes the issue for you

**Comment by rawls238** [comment]
@BGordts did this fix the issue for you?

**Comment by BGordts** [comment]
Yep, works perfectly now. Thanks a lot!
